export const SEARCH_MOVIE_VALUE = 'SEARCH_MOVIE_VALUE';
export const SET_SEARCH_CATEGORY = 'SET_SEARCH_CATEGORY';
export const SET_FILTER_CATEGORY = 'SET_FILTER_CATEGORY';
export const SET_MOVIES = 'SET_MOVIES';
export const LOADER_DISPLAY_ON = 'LOADER_DISPLAY_ON';
export const LOADER_DISPLAY_OFF = 'LOADER_DISPLAY_OFF';
